--
-- PostgreSQL database dump
--

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: favorite_list_movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorite_list_movies (
    list_movie_id integer NOT NULL,
    list_id integer NOT NULL,
    movie_id integer NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    added_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.favorite_list_movies OWNER TO postgres;

--
-- Name: COLUMN favorite_list_movies.sort_order; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.favorite_list_movies.sort_order IS 'Järjestys listassa';


--
-- Name: favorite_list_movies_list_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favorite_list_movies ALTER COLUMN list_movie_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_list_movies_list_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_lists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorite_lists (
    list_id integer NOT NULL,
    user_id integer NOT NULL,
    list_name character varying(255) NOT NULL,
    share_url character varying(255),
    is_default boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.favorite_lists OWNER TO postgres;

--
-- Name: COLUMN favorite_lists.list_name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.favorite_lists.list_name IS 'Suosikkilistan nimi, esim "Omat suosikit"';


--
-- Name: COLUMN favorite_lists.share_url; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.favorite_lists.share_url IS 'Jaettava URI, null jos ei jaettu';


--
-- Name: COLUMN favorite_lists.is_default; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.favorite_lists.is_default IS 'Onko käyttäjän oletuslista';


--
-- Name: favorite_lists_list_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favorite_lists ALTER COLUMN list_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorite_lists_list_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_members; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.group_members (
    member_id integer NOT NULL,
    group_id integer NOT NULL,
    user_id integer NOT NULL,
    status character varying(20) DEFAULT 'pending'::character varying NOT NULL,
    joined_at timestamp without time zone,
    requested_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.group_members OWNER TO postgres;

--
-- Name: COLUMN group_members.status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_members.status IS 'pending, approved, rejected';


--
-- Name: group_members_member_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.group_members ALTER COLUMN member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_members_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.group_movies (
    group_movie_id integer NOT NULL,
    group_id integer NOT NULL,
    movie_id integer NOT NULL,
    added_by_user_id integer NOT NULL,
    added_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.group_movies OWNER TO postgres;

--
-- Name: COLUMN group_movies.added_by_user_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_movies.added_by_user_id IS 'Kuka lisäsi';


--
-- Name: group_movies_group_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.group_movies ALTER COLUMN group_movie_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_movies_group_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_showtimes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.group_showtimes (
    group_showtime_id integer NOT NULL,
    group_id integer NOT NULL,
    movie_id integer,
    theater_name character varying(255) NOT NULL,
    movie_title character varying(255) NOT NULL,
    showtime timestamp without time zone NOT NULL,
    finnkino_id character varying(50),
    added_by_user_id integer NOT NULL,
    added_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.group_showtimes OWNER TO postgres;

--
-- Name: COLUMN group_showtimes.movie_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_showtimes.movie_id IS 'Yhdistys sovelluksen elokuvaan';


--
-- Name: COLUMN group_showtimes.theater_name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_showtimes.theater_name IS 'Teatteri';


--
-- Name: COLUMN group_showtimes.movie_title; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_showtimes.movie_title IS 'Elokuvan nimi Finnkino API:sta';


--
-- Name: COLUMN group_showtimes.showtime; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_showtimes.showtime IS 'Esitysaika';


--
-- Name: COLUMN group_showtimes.finnkino_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.group_showtimes.finnkino_id IS 'Finnkino API ID';


--
-- Name: group_showtimes_group_showtime_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.group_showtimes ALTER COLUMN group_showtime_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_showtimes_group_showtime_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.groups (
    group_id integer NOT NULL,
    group_name character varying(255) NOT NULL,
    owner_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.groups OWNER TO postgres;

--
-- Name: COLUMN groups.group_name; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.groups.group_name IS 'Ryhmän nimi';


--
-- Name: COLUMN groups.owner_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.groups.owner_id IS 'Ryhmän luoja/omistaja';


--
-- Name: groups_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.groups ALTER COLUMN group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movies (
    movie_id integer NOT NULL,
    tmdb_id character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    poster_url character varying(500),
    release_year integer,
    genre character varying(255),
    tmdb_rating double precision,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.movies OWNER TO postgres;

--
-- Name: COLUMN movies.tmdb_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.movies.tmdb_id IS 'The Movie Database ID';


--
-- Name: movies_movie_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movies ALTER COLUMN movie_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_movie_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reviews (
    review_id integer NOT NULL,
    user_id integer NOT NULL,
    movie_id integer NOT NULL,
    review_text text NOT NULL,
    rating integer NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.reviews OWNER TO postgres;

--
-- Name: COLUMN reviews.rating; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.reviews.rating IS '1-5 tähteä';


--
-- Name: reviews_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reviews ALTER COLUMN review_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: COLUMN users.email; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.users.email IS 'Käyttäjätunnus';


--
-- Name: COLUMN users.password_hash; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.users.password_hash IS 'Min 8 merkkiä, iso kirjain, numero';


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorite_list_movies favorite_list_movies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_list_movies
    ADD CONSTRAINT favorite_list_movies_pkey PRIMARY KEY (list_movie_id);


--
-- Name: favorite_lists favorite_lists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_lists
    ADD CONSTRAINT favorite_lists_pkey PRIMARY KEY (list_id);


--
-- Name: favorite_lists favorite_lists_share_url_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_lists
    ADD CONSTRAINT favorite_lists_share_url_key UNIQUE (share_url);


--
-- Name: group_members group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_pkey PRIMARY KEY (member_id);


--
-- Name: group_movies group_movies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_movies
    ADD CONSTRAINT group_movies_pkey PRIMARY KEY (group_movie_id);


--
-- Name: group_showtimes group_showtimes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_showtimes
    ADD CONSTRAINT group_showtimes_pkey PRIMARY KEY (group_showtime_id);


--
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (group_id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (movie_id);


--
-- Name: movies movies_tmdb_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_tmdb_id_key UNIQUE (tmdb_id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (review_id);


--
-- Name: group_members uq_group_members_group_user; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT uq_group_members_group_user UNIQUE (group_id, user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: favorite_list_movies_list_id_movie_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX favorite_list_movies_list_id_movie_id_idx ON public.favorite_list_movies USING btree (list_id, movie_id);


--
-- Name: favorite_lists_user_id_is_default_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX favorite_lists_user_id_is_default_idx ON public.favorite_lists USING btree (user_id, is_default);


--
-- Name: group_members_group_id_user_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX group_members_group_id_user_id_idx ON public.group_members USING btree (group_id, user_id);


--
-- Name: group_movies_group_id_movie_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX group_movies_group_id_movie_id_idx ON public.group_movies USING btree (group_id, movie_id);


--
-- Name: reviews_user_id_movie_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX reviews_user_id_movie_id_idx ON public.reviews USING btree (user_id, movie_id);


--
-- Name: favorite_list_movies favorite_list_movies_list_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_list_movies
    ADD CONSTRAINT favorite_list_movies_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.favorite_lists(list_id);


--
-- Name: favorite_list_movies favorite_list_movies_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_list_movies
    ADD CONSTRAINT favorite_list_movies_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(movie_id);


--
-- Name: favorite_lists favorite_lists_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorite_lists
    ADD CONSTRAINT favorite_lists_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: group_members group_members_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(group_id) ON DELETE CASCADE;


--
-- Name: group_members group_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: group_movies group_movies_added_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_movies
    ADD CONSTRAINT group_movies_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.users(user_id);


--
-- Name: group_movies group_movies_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_movies
    ADD CONSTRAINT group_movies_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(group_id);


--
-- Name: group_movies group_movies_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_movies
    ADD CONSTRAINT group_movies_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(movie_id);


--
-- Name: group_showtimes group_showtimes_added_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_showtimes
    ADD CONSTRAINT group_showtimes_added_by_user_id_fkey FOREIGN KEY (added_by_user_id) REFERENCES public.users(user_id);


--
-- Name: group_showtimes group_showtimes_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_showtimes
    ADD CONSTRAINT group_showtimes_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(group_id);


--
-- Name: group_showtimes group_showtimes_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.group_showtimes
    ADD CONSTRAINT group_showtimes_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(movie_id);


--
-- Name: groups groups_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(user_id);


--
-- Name: reviews reviews_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movies(movie_id);


--
-- Name: reviews reviews_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
